### ISSUE TITLE
A problem about the package"tree"

### ISSUE THREAD

**Issue by Xiechangsheng** [blt2114/ProtDiff_SMCDiff#1]
Could you give me some details about the package 'tree' you use, including its full name, which category it belongs to, e.g. I keep having problems trying to parse it with the ipython notebook
ok I find it

**Comment by blt2114** [comment]
Have you installed it into a conda environment from the yml?

From our requirements file, the dependency should be:
`    - dm-tree==0.1.6`

**Comment by blt2114** [comment]
(closing this now due to inactivity).
